### ISSUE TITLE
Building with pyo3 and maturin works with default linker, but not with mold

### ISSUE THREAD

**Issue by nipunn1313** [rui314/mold#1233]
```
/Users/nipunn/src/sold/build/ld64 -v
mold (sold) 1.11.0 (a52e8b37661562c866a579ab1164f94694f479a5; compatible with GNU ld)
```

Repro
```
git clone https://github.com/get-convex/convex-py
# Current head at the time of the bugreport
git checkout de180ceec1a08ed78cb290f333a50c64ed5f47b6 

# Build
poetry install --no-root && poetry run maturin dev

# Run
poetry run python -c "import _convex"
```

If I build with regular linker, this works

If I build with mold, I get this
```
poetry run python -c "import _convex"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/nipunn/src/convex-py/python/_convex/__init__.py", line 9, in <module>
    from ._convex import (
ImportError: dlopen(/Users/nipunn/src/convex-py/python/_convex/_convex.abi3.so, 0x0002): weak-def symbol not found '_PyBaseObject_Type'
```

To configure mold, I added this to .cargo/config.toml (I built mold from source)
```
[build]
rustflags = ["-C", "link-arg=-fuse-ld=/Users/nipunn/src/sold/build/ld64"]
```

In case it is helpful, here is some more debugging info
```
otool -L _convex.abi3.ld.so
_convex.abi3.ld.so:
	@rpath/_convex.abi3.so (compatibility version 0.0.0, current version 0.0.0)
	/System/Library/Frameworks/Security.framework/Versions/A/Security (compatibility version 1.0.0, current version 61123.100.169)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 2420.0.0)
	/usr/lib/libiconv.2.dylib (compatibility version 7.0.0, current version 7.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1345.100.2)
otool -L _convex.abi3.mold.so
_convex.abi3.mold.so:
	/System/Library/Frameworks/Security.framework/Versions/A/Security (compatibility version 0.0.0, current version 0.0.0)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libiconv.2.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libobjc.A.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/_convex.abi3.so (compatibility version 0.0.0, current version 0.0.0)
```

**Comment by rui314** [comment]
sold is not actively maintained anymore, as Apple's ld-prime linker got as fast as the sold linker. Please use ld-prime on macOS.
