### ISSUE TITLE
XWayland segfaults when linked with mold

### ISSUE THREAD

**Issue by aidanharris** [rui314/mold#1235]
I first saw this on my Gentoo system (I'm using mold as a system-wide linker) but I've been able to reproduce it in Archlinux too. I believe it's a recent regression. If that's the case I'll try to track down the broken commit.

I'll give instructions on how to reproduce it in Arch below:

## Install xorg-xwayland from the Arch repositories
```
pacman -S xorg-xwayland
```
##  In a Wayland compositor (I am using Sway because it makes for a simple environment to reproduce it in. I can't even run my usual KDE Plasma desktop because Qt segfaults on start because of the failing XWayland) run XWayland like the following
`Xwayland -decorate :90`

It should work and you should see a window open like the following (nothing very interesting is happening, it's just a blank XServer with nothing running in it)
![Screenshot from 2024-04-15 11:14:44](https://github.com/rui314/mold/assets/3309784/30217349-1e5e-42d5-ade5-95ccfe79578a)

### First build and install mold-git from the AUR
```
# Install mold
pacman -Sy --needed base-devel git
git clone https://aur.archlinux.org/mold-git.git mold-git
cd mold-git
makepkg -siCcf
```

### Then edit /etc/makepkg.conf to use mold as the system linker
```diff
diff -Naur a b
diff -Naur a/etc/makepkg.conf b/etc/makepkg.conf
--- a/etc/makepkg.conf	2024-04-15 11:20:37.805418225 +0000
+++ b/etc/makepkg.conf	2024-04-15 11:21:05.135509183 +0000
@@ -46,7 +46,7 @@
         -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer"
 CXXFLAGS="$CFLAGS -Wp,-D_GLIBCXX_ASSERTIONS"
 LDFLAGS="-Wl,-O1 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now \
-         -Wl,-z,pack-relative-relocs"
+         -Wl,-z,pack-relative-relocs -fuse-ld=mold"
 LTOFLAGS="-flto=auto"
 RUSTFLAGS="-Cforce-frame-pointers=yes"
 #-- Make Flags: change this for DistCC/SMP systems
```

### Now re-build xorg-xwayland
```
git clone https://gitlab.archlinux.org/archlinux/packaging/packages/xorg-xwayland.git
cd xorg-xwayland
makepkg -siCcf
```
### Now when we run XWayland it will crash at startup
```
Failed to initialize glamor, falling back to sw
(EE) 
(EE) Backtrace:
(EE) 0: Xwayland (0x63e51baff000+0x19cab3) [0x63e51bc9bab3]
(EE) 1: Xwayland (0x63e51baff000+0x19cbb6) [0x63e51bc9bbb6]
(EE) 2: /usr/lib/libc.so.6 (0x7ee1b8b45000+0x3c770) [0x7ee1b8b81770]
(EE) 3: /usr/lib/libxkbfile.so.1 (XkbWriteXKBKeymapForNames+0x15a) [0x7ee1b90c3d0a]
(EE) 4: Xwayland (0x63e51baff000+0x176af9) [0x63e51bc75af9]
(EE) 5: Xwayland (0x63e51baff000+0x1da3b2) [0x63e51bcd93b2]
(EE) 6: Xwayland (0x63e51baff000+0x17727e) [0x63e51bc7627e]
(EE) 7: Xwayland (0x63e51baff000+0x1db640) [0x63e51bcda640]
(EE) 8: Xwayland (0x63e51baff000+0xc838b) [0x63e51bbc738b]
(EE) 9: Xwayland (0x63e51baff000+0xd1197) [0x63e51bbd0197]
(EE) 10: Xwayland (0x63e51baff000+0x875e3) [0x63e51bb865e3]
(EE) 11: /usr/lib/libc.so.6 (0x7ee1b8b45000+0x25cd0) [0x7ee1b8b6acd0]
(EE) 12: /usr/lib/libc.so.6 (__libc_start_main+0x8a) [0x7ee1b8b6ad8a]
(EE) 13: Xwayland (0x63e51baff000+0x5eb15) [0x63e51bb5db15]
(EE) 
(EE) Segmentation fault at address 0xaf
(EE) 
Fatal server error:
(EE) Caught signal 11 (Segmentation fault). Server aborting
(EE) 
syntax error: line 1 of stdin
Errors encountered in stdin; not compiled.
```

The full backtrace from my Gentoo machine is below:
```
[New LWP 7781]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `Xwayland -decorate :90'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007759e26c2f1c in __pthread_kill_implementation () from /lib64/libc.so.6
Thread 1 (Thread 0x7759e1fbf8c0 (LWP 7781)):
#0  0x00007759e26c2f1c in __pthread_kill_implementation () from /lib64/libc.so.6
No symbol table info available.
#1  0x00007759e2672352 in raise () from /lib64/libc.so.6
No symbol table info available.
#2  0x00007759e265a4ed in abort () from /lib64/libc.so.6
No symbol table info available.
#3  0x000058562e0d80c2 in OsAbort () at ../xwayland-23.2.6/os/utils.c:1363
No locals.
#4  0x000058562e0d8399 in AbortServer () at ../xwayland-23.2.6/os/log.c:879
No locals.
#5  FatalError (f=f@entry=0x58562dfeb8d0 "Caught signal %d (%s). Server aborting\n") at ../xwayland-23.2.6/os/log.c:1017
        args = {{gp_offset = 24, fp_offset = 48, overflow_arg_area = 0x7ffe7550a7e0, reg_save_area = 0x7ffe7550a720}}
        args2 = {{gp_offset = 8, fp_offset = 48, overflow_arg_area = 0x7ffe7550a7e0, reg_save_area = 0x7ffe7550a720}}
        beenhere = 1
#6  0x000058562e0d8495 in OsSigHandler (unused=<optimized out>, sip=<optimized out>, signo=11) at ../xwayland-23.2.6/os/osinit.c:156
No locals.
#7  OsSigHandler (signo=11, sip=<optimized out>, unused=<optimized out>) at ../xwayland-23.2.6/os/osinit.c:110
No locals.
#8  <signal handler called>
No symbol table info available.
#9  0x00007759e2f9ce68 in XkbWriteXKBKeymapForNames (file=0x58562ff14df0, names=0x7ffe7550d610, dpy=0x0, xkb=0x7f, want=119, need=6) at /usr/src/debug/x11-libs/libxkbfile-1.1.3/libxkbfile-1.1.3/src/xkbmisc.c:266
        name = 0x7759e2f8e6e0 "default"
        tmp = <optimized out>
        complete = 55
        old_names = <optimized out>
        multi_section = <optimized out>
        wantNames = <optimized out>
        wantConfig = <optimized out>
        wantDflts = <optimized out>
        finfo = {type = 0, defined = 0, xkb = 0x0}
#10 0x000058562e0bab3d in RunXkbComp (callback=0x58562e0b82a0 <xkb_write_keymap_for_names_cb>, userdata=0x7ffe7550d580) at ../xwayland-23.2.6/xkb/ddxLoad.c:179
        out = 0x58562ff14df0
        buf = 0x58562ffb07a0 "\"/usr/bin/xkbcomp\" -w 1 \"-R/usr/share/X11/xkb\" -xkm \"-\" -em1 \"The XKEYBOARD keymap compiler (xkbcomp) reports:\" -emp \"> \" -eml \"Errors from xkbcomp are not fatal to the X server\" \"/run/user/1000/serve"...
        keymap = "server-90\000\376/VX\000\000P\300\376/VX\000\000@\276\376/VX\000\000p\276\376/VX\000\000\240\276\376/VX\000\000о\376/VX\000\000\000\277\376/VX\000\0000\277\376/VX\000\000\200\300\376/VX\000\000\260\300\376/VX\000\000\340\300\376/VX\000\000\020\301\376/VX\000\000@\301\376/VX\000\000p\301\376/VX\000\000(r\b\342Yw\000\000\n\000\000\000\000\000\000\000\002\000\000\000\000\000\000\000\006\000\000\000\000\000\000\200", '\000' <repeats 37 times>, "\377\377\377\000\000\000\000\000\000\377\377\320"...
        xkm_output_dir = "/run/user/1000/\000&", '\000' <repeats 15 times>, "\350\333d\342Yw\000\000\220\257\324\342Yw\000\000(\266Pu\376\177\000\000$\266Pu\376\177\000\000$u\202\r\000\000\000\000\272\234\240\340Yw\000\000{,\t\343Yw\000\000\306\t\000\000\000\000\000\000\000[\240\340Yw\000\000VNr", '\000' <repeats 13 times>, "(r\b\342Yw\000\000%\232\240\340Yw\000\000\000\267Pu\376\177\000\000\350\333\361/VX\000\000\317ړ\034\000\000\000\000\200\241\361/VX\000\000 \245\361/VX\000\000Q6\t\343Yw\000\000\020\000\000\000\000\000\000\000\350\333\361/VX\000\000\001"...
        emptystring = <optimized out>
        xkbbasedirflag = 0x58562ffff460 ""
        xkbbindir = 0x58562dfe337d "/usr/bin"
        xkbbindirsep = 0x58562dfe423d "/"
        xkmfile = 0x58562dfea4b9 "-"
        ld = <optimized out>
        lps = <optimized out>
#11 0x000058562e103f98 in XkbDDXCompileKeymapByNames (nameRtrnLen=4096, nameRtrn=0x7ffe7550d638 "\340\305\0020VX", need=87, want=127, names=<optimized out>, xkb=<optimized out>) at ../xwayland-23.2.6/xkb/ddxLoad.c:250
        keymap = <optimized out>
        rc = 0
        ctx = {xkb = 0x0, names = 0x7ffe7550d610, want = 127, need = 87}
        keymap = <optimized out>
        rc = <optimized out>
        ctx = <optimized out>
#12 XkbDDXLoadKeymapByNames.constprop.0 (keybd=<optimized out>, names=<optimized out>, want=127, need=87, xkbRtrn=0x7ffe7550d5e8, nameRtrn=0x7ffe7550d638 "\340\305\0020VX", nameRtrnLen=4096) at ../xwayland-23.2.6/xkb/ddxLoad.c:391
        xkb = <optimized out>
#13 0x000058562e0bafa5 in XkbCompileKeymapForDevice (dev=0x58562fff75a0, rmlvo=<optimized out>, need=87) at ../xwayland-23.2.6/xkb/ddxLoad.c:478
        xkb = 0x0
        provided = <optimized out>
        kccgst = {keycodes = 0x0, types = 0x58563002c5c0 "evdev+aliases(qwerty)", compat = 0x58563002c620 "complete", symbols = 0x58563002c600 "complete", geometry = 0x58563002c640 "pc+us+inet(evdev)"}
        name = "\340\305\0020VX\000\000re/X11/xkb/rules/evdev\000\000\000\000\000\000\000\000\000\000 k\177\342Yw\000\000\000\000\000\000\000\000\000\000$\002\000\000$\002\000\000$\002\000\000$\002\000\000 k\177\342Yw\000\000\000\000\000\000\000\000\000\000\b\000\000\000\b\000\000\000\b\000\000\000\b", '\000' <repeats 13 times>, " \000\000\000 \000\000\000\000\000\000\000\000\000\000   \000   ", '?' <repeats 16 times>, '\231' <repeats 16 times>, ' ' <repeats 16 times>, '\000' <repeats 48 times>...
#14 0x000058562e10a4cb in XkbCompileKeymap (rmlvo=<optimized out>, dev=0x58562fff75a0) at ../xwayland-23.2.6/xkb/ddxLoad.c:531
        xkb = <optimized out>
        need = 87
        xkb = <optimized out>
        need = <optimized out>
#15 InitKeyboardDeviceStructInternal.constprop.0 (dev=0x58562fff75a0, keymap=keymap@entry=0x0, keymap_length=keymap_length@entry=0, bell_func=bell_func@entry=0x58562e03a1fa <CoreKeyboardBell>, ctrl_func=ctrl_func@entry=0x58562e03a1fb <CoreKeyboardCtl>, rmlvo=<optimized out>) at ../xwayland-23.2.6/xkb/xkbInit.c:570
        i = <optimized out>
        check = 0
        xkbi = 0x58562fffb6d0
        xkb = <optimized out>
        sli = <optimized out>
        changes = {device_spec = 0, state_changes = 0, map = {changed = 0, min_key_code = 0 '\000', max_key_code = 0 '\000', first_type = 0 '\000', num_types = 0 '\000', first_key_sym = 0 '\000', num_key_syms = 0 '\000', first_key_act = 0 '\000', num_key_acts = 0 '\000', first_key_behavior = 0 '\000', num_key_behaviors = 0 '\000', first_key_explicit = 0 '\000', num_key_explicit = 0 '\000', first_modmap_key = 0 '\000', num_modmap_keys = 0 '\000', first_vmodmap_key = 0 '\000', num_vmodmap_keys = 0 '\000', pad = 0 '\000', vmods = 0}, ctrls = {changed_ctrls = 0, enabled_ctrls_changes = 0, num_groups_changed = 0}, indicators = {state_changes = 0, map_changes = 0}, names = {changed = 0, first_type = 0 '\000', num_types = 0 '\000', first_lvl = 0 '\000', num_lvls = 0 '\000', num_aliases = 0 '\000', num_rg = 0 '\000', first_key = 0 '\000', num_keys = 0 '\000', changed_vmods = 0, changed_indicators = 0, changed_groups = 0 '\000'}, compat = {changed_groups = 0 '\000', first_si = 0, num_si = 0}}
        cause = <optimized out>
        rmlvo_dflts = {rules = 0x58562fffb540 "evdev", model = 0x58562fffb560 "pc105", layout = 0x58562fffb580 "us", variant = 0x58562fffb5a0 "", options = 0x58562fffb5c0 ""}
        __func__ = <optimized out>
#16 0x000058562e03bbec in InitKeyboardDeviceStruct (rmlvo=0x0, ctrl_func=0x58562e03a1fb <CoreKeyboardCtl>, bell_func=0x58562e03a1fa <CoreKeyboardBell>, dev=<optimized out>) at ../xwayland-23.2.6/xkb/xkbInit.c:667
No locals.
#17 CoreKeyboardProc (pDev=<optimized out>, what=0) at ../xwayland-23.2.6/dix/devices.c:643
No locals.
#18 0x000058562e0413e7 in ActivateDevice (dev=0x58562fff75a0, sendevent=sendevent@entry=1 '\001') at ../xwayland-23.2.6/dix/devices.c:596
        ret = 0
        pScreen = 0x58562fefa050
#19 0x000058562e0414f7 in InitCoreDevices () at ../xwayland-23.2.6/dix/devices.c:746
        result = <optimized out>
#20 0x000058562e010dec in dix_main (envp=<optimized out>, argv=<optimized out>, argc=<optimized out>) at ../xwayland-23.2.6/dix/main.c:244
        i = 1
        alwaysCheckForInput = {0, 1}
        i = <optimized out>
        alwaysCheckForInput = <optimized out>
        pScreen = <optimized out>
        pScreen = <optimized out>
        remember_it = <optimized out>
        pScreen = <optimized out>
#21 main (argc=3, argv=0x7ffe7550ee08, envp=<optimized out>) at ../xwayland-23.2.6/dix/stubmain.c:34
No locals.
```

**Comment by aidanharris** [comment]
No segfault with sys-devel/mold-2.30.0

**Comment by aidanharris** [comment]
Seems like the latest commit is what broke things but I don't know enough to know why:
```
dfa26d08823ca0c8b74773823a4909e988bc6740 is the first bad commit
commit dfa26d08823ca0c8b74773823a4909e988bc6740
Author: Rui Ueyama
Date:   Sun Apr 14 15:03:53 2024 +0900

    1;10;0cGive symbols in .so higher priority than those in .a
    
    Previously, .so and .a were of the same priority and therefore symbols
    in those were resolved based on their positions in the command line;
    whichever file appears first in the command line took precedence.
    
    Here is the problem we are trying to solve with this change: KiCad
    passes unnecessary .a files to the linker along with some .so files.
    Some symbols are defined both by .a and by .so.
    
    If a symbol is resolved from .a, the linker pulls out the file from
    the archive, but because the .a file does not really provide a
    complete set of object files, it ended with "undefined symbol" error.
    
    If a symbol is resolved from .so, everything is fine.
    
    This is arguably a bug in KiCad, or at least depending on the order of
    files in the command line is very fragile. But maybe this change could
    fix the issue without too much side effects. So let's see how it goes.
    
    Fixes https://github.com/rui314/mold/discussions/1234

 elf/input-files.cc       | 38 ++++++++++++++++++++------------------
 elf/input-sections.cc    |  1 +
 test/elf/dso-weak-def.sh | 30 ++++++++++++++++++++++++++++++
 test/elf/link-order.sh   | 22 ----------------------
 4 files changed, 51 insertions(+), 40 deletions(-)
 create mode 100755 test/elf/dso-weak-def.sh
 delete mode 100755 test/elf/link-order.sh
bisect found first bad commit

**Comment by rui314** [comment]
Thank you for reporting the problem and bisecting. That's the very last commit I've made to the repo, and it caused very subtle issues to other programs, so I think I need to revert it.
