### ISSUE TITLE
Crash in `mold::elf::GdbIndexSection<mold::elf::X86_64>::copy_buf()`

### ISSUE THREAD

**Issue by mrichtarsky** [rui314/mold#472]
Hi,

with `--gdb-index` I'm getting a reproducible crash here:

```
Thread 4.6 "ld" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff5412700 (LWP 60835)]
0x00000000007025ff in std::__atomic_base<unsigned int>::store (__m=std::memory_order::seq_cst, __i=268435471, this=0) at /h/gcc-10.2.1+git583-1.3.4.sap20201215-linuxx86_64-linuxx86_64/include/c++/10/bits/atomic_base.h:404
404             __atomic_store_n(&_M_i, __i, int(__m));
(gdb) bt
#0  0x00000000007025ff in std::__atomic_base<unsigned int>::store (__m=std::memory_order::seq_cst, __i=268435471, this=0) at /h/gcc-10.2.1+git583-1.3.4.sap20201215-linuxx86_64-linuxx86_64/include/c++/10/bits/atomic_base.h:404
#1  std::__atomic_base<unsigned int>::operator= (this=0, __i=268435471) at /h/gcc-10.2.1+git583-1.3.4.sap20201215-linuxx86_64-linuxx86_64/include/c++/10/bits/atomic_base.h:297
#2  0x00000000006f0f2a in mold::elf::GdbIndexSection<mold::elf::X86_64>::copy_buf(mold::elf::Context<mold::elf::X86_64>&)::{lambda(mold::elf::ObjectFile<mold::elf::X86_64>*)#1}::operator()(mold::elf::ObjectFile<mold::elf::X86_64>*) const (this=0x411f81145e0, file=0x411f8223c00) at elf/output-chunks.cc:2305
#3  0x0000000000809e8d in tbb::detail::d2::parallel_for_each_operator_selector<mold::elf::GdbIndexSection<mold::elf::X86_64>::copy_buf(mold::elf::Context<mold::elf::X86_64>&)::{lambda(mold::elf::ObjectFile<mold::elf::X86_64>*)#1}>::call<mold::elf::ObjectFile<mold::elf::X86_64>*&, tbb::detail::d2::feeder_impl<mold::elf::GdbIndexSection<mold::elf::X86_64>::copy_buf(mold::elf::Context<mold::elf::X86_64>&)::{lambda(mold::elf::ObjectFile<mold::elf::X86_64>*)#1}, mold::elf::ObjectFile<mold::elf::X86_64>*> >(mold::elf::GdbIndexSection<mold::elf::X86_64>::copy_buf(mold::elf::Context<mold::elf::X86_64>&)::{lambda(mold::elf::ObjectFile<mold::elf::X86_64>*)#1} const&, mold::elf::ObjectFile<mold::elf::X86_64>*&, tbb::detail::d2::feeder_impl<mold::elf::GdbIndexSection<mold::elf::X86_64>::copy_buf(mold::elf::Context<mold::elf::X86_64>&)::{lambda(mold::elf::ObjectFile<mold::elf::X86_64>*)#1}, mold::elf::ObjectFile<mold::elf::X86_64>*>*) (body=..., item=@0x411f8410088: 0x411f8223c00) at third-party/tbb/include/tbb/../oneapi/tbb/parallel_for_each.h:95
#4  0x0000000000801fbc in tbb::detail::d2::parallel_for_body_wrapper<__gnu_cxx::__normal_iterator<mold::elf::ObjectFile<mold::elf::X86_64>**, std::vector<mold::elf::ObjectFile<mold::elf::X86_64>*, std::allocator<mold::elf::ObjectFile<mold::elf::X86_64>*> > >, mold::elf::GdbIndexSection<mold::elf::X86_64>::copy_buf(mold::elf::Context<mold::elf::X86_64>&)::{lambda(mold::elf::ObjectFile<mold::elf::X86_64>*)#1}, mold::elf::ObjectFile<mold::elf::X86_64>*>::operator()(tbb::detail::d1::blocked_range<unsigned long>) const (this=0x41240021358, range=...) at third-party/tbb/include/tbb/../oneapi/tbb/parallel_for_each.h:400
#5  0x00000000007fc3a0 in tbb::detail::d1::start_for<tbb::detail::d1::blocked_range<unsigned long>, tbb::detail::d2::parallel_for_body_wrapper<__gnu_cxx::__normal_iterator<mold::elf::ObjectFile<mold::elf::X86_64>**, std::vector<mold::elf::ObjectFile<mold::elf::X86_64>*, std::allocator<mold::elf::ObjectFile<mold::elf::X86_64>*> > >, mold::elf::GdbIndexSection<mold::elf::X86_64>::copy_buf(mold::elf::Context<mold::elf::X86_64>&)::{lambda(mold::elf::ObjectFile<mold::elf::X86_64>*)#1}, mold::elf::ObjectFile<mold::elf::X86_64>*>, tbb::detail::d1::auto_partitioner const>::run_body(tbb::detail::d1::blocked_range<unsigned long>&) (this=warning: RTTI symbol not found for class 'tbb::detail::d1::start_for<tbb::detail::d1::blocked_range<unsigned long>, tbb::detail::d2::parallel_for_body_wrapper<__gnu_cxx::__normal_iterator<mold::elf::ObjectFile<mold::elf::X86_64>**, std::vector<mold::elf::ObjectFile<mold::elf::X86_64>*, std::allocator<mold::elf::ObjectFile<mold::elf::X86_64>*> > >, mold::elf::GdbIndexSection<mold::elf::X86_64>::copy_buf(mold::elf::Context<mold::elf::X86_64>&)::{lambda(mold::elf::ObjectFile<mold::elf::X86_64>*)#1}, mold::elf::ObjectFile<mold::elf::X86_64>*>, tbb::detail::d1::auto_partitioner const>'0x41240021300, r=...) at third-party/tbb/include/tbb/../oneapi/tbb/parallel_for.h:119
#6  0x00000000007f2ce0 in tbb::detail::d1::dynamic_grainsize_mode<tbb::detail::d1::adaptive_mode<tbb::detail::d1::auto_partition_type> >::work_balance<tbb::detail::d1::start_for<tbb::detail::d1::blocked_range<unsigned long>, tbb::detail::d2::parallel_for_body_wrapper<__gnu_cxx::__normal_iterator<mold::elf::ObjectFile<mold::elf::X86_64>**, std::vector<mold::elf::ObjectFile<mold::elf::X86_64>*, std::allocator<mold::elf::ObjectFile<mold::elf::X86_64>*> > >, mold::elf::GdbIndexSection<mold::elf::X86_64>::copy_buf(mold::elf::Context<mold::elf::X86_64>&)::{lambda(mold::elf::ObjectFile<mold::elf::X86_64>*)#1}, mold::elf::ObjectFile<mold::elf::X86_64>*>, tbb::detail::d1::auto_partitioner const>, tbb::detail::d1::blocked_range<unsigned long> >(tbb::detail::d1::start_for<tbb::detail::d1::blocked_range<unsigned long>, tbb::detail::d2::parallel_for_body_wrapper<__gnu_cxx::__normal_iterator<mold::elf::ObjectFile<mold::elf::X86_64>**, std::vector<mold::elf::ObjectFile<mold::elf::X86_64>*, std::allocator<mold::elf::ObjectFile<mold::elf::X86_64>*> > >, mold::elf::GdbIndexSection<mold::elf::X86_64>::copy_buf(mold::elf::Context<mold::elf::X86_64>&)::{lambda(mold::elf::ObjectFile<mold::elf::X86_64>*)#1}, mold::elf::ObjectFile<mold::elf::X86_64>*>, tbb::detail::d1::auto_partitioner const>&, tbb::detail::d1::blocked_range<unsigned long>&, tbb::detail::d1::execution_data&) (this=0x41240021378, start=..., range=..., ed=...) at third-party/tbb/include/tbb/../oneapi/tbb/partitioner.h:447(oo
#7  0x00000000007eafea in tbb::detail::d1::partition_type_base<tbb::detail::d1::auto_partition_type>::execute<tbb::detail::d1::start_for<tbb::detail::d1::blocked_range<unsigned long>, tbb::detail::d2::parallel_for_body_wrapper<__gnu_cxx::__normal_iterator<mold::elf::ObjectFile<mold::elf::X86_64>**, std::vector<mold::elf::ObjectFile<mold::elf::X86_64>*, std::allocator<mold::elf::ObjectFile<mold::elf::X86_64>*> > >, mold::elf::GdbIndexSection<mold::elf::X86_64>::copy_buf(mold::elf::Context<mold::elf::X86_64>&)::{lambda(mold::elf::ObjectFile<mold::elf::X86_64>*)#1}, mold::elf::ObjectFile<mold::elf::X86_64>*>, tbb::detail::d1::auto_partitioner const>, tbb::detail::d1::blocked_range<unsigned long> >(tbb::detail::d1::start_for<tbb::detail::d1::blocked_range<unsigned long>, tbb::detail::d2::parallel_for_body_wrapper<__gnu_cxx::__normal_iterator<mold::elf::ObjectFile<mold::elf::X86_64>**, std::vector<mold::elf::ObjectFile<mold::elf::X86_64>*, std::allocator<mold::elf::ObjectFile<mold::elf::X86_64>*> > >, mold::elf::GdbIndexSection<mold::elf::X86_64>::copy_buf(mold::elf::Context<mold::elf::X86_64>&)::{lambda(mold::elf::ObjectFile<mold::elf::X86_64>*)#1}, mold::elf::ObjectFile<mold::elf::X86_64>*>, tbb::detail::d1::auto_partitioner const>&, tbb::detail::d1::blocked_range<unsigned long>&, tbb::detail::d1::execution_data&) (this=0x41240021378, start=..., range=..., ed=...) at third-party/tbb/include/tbb/../oneapi/tbb/partitioner.h:288
#8  0x00000000007e6648 in tbb::detail::d1::start_for<tbb::detail::d1::blocked_range<unsigned long>, tbb::detail::d2::parallel_for_body_wrapper<__gnu_cxx::__normal_iterator<mold::elf::ObjectFile<mold::elf::X86_64>**, std::vector<mold::elf::ObjectFile<mold::elf::X86_64>*, std::allocator<mold::elf::ObjectFile<mold::elf::X86_64>*> > >, mold::elf::GdbIndexSection<mold::elf::X86_64>::copy_buf(mold::elf::Context<mold::elf::X86_64>&)::{lambda(mold::elf::ObjectFile<mold::elf::X86_64>*)#1}, mold::elf::ObjectFile<mold::elf::X86_64>*>, tbb::detail::d1::auto_partitioner const>::execute(tbb::detail::d1::execution_data&) (this=warning: RTTI symbol not found for class 'tbb::detail::d1::start_for<tbb::detail::d1::blocked_range<unsigned long>, tbb::detail::d2::parallel_for_body_wrapper<__gnu_cxx::__normal_iterator<mold::elf::ObjectFile<mold::elf::X86_64>**, std::vector<mold::elf::ObjectFile<mold::elf::X86_64>*, std::allocator<mold::elf::ObjectFile<mold::elf::X86_64>*> > >, mold::elf::GdbIndexSection<mold::elf::X86_64>::copy_buf(mold::elf::Context<mold::elf::X86_64>&)::{lambda(mold::elf::ObjectFile<mold::elf::X86_64>*)#1}, mold::elf::ObjectFile<mold::elf::X86_64>*>, tbb::detail::d1::auto_partitioner const>'0x41240021300, ed=...) at third-party/tbb/include/tbb/../oneapi/tbb/parallel_for.h:172
#9  0x0000000000b99fc5 in tbb::detail::r1::task_dispatcher::local_wait_for_all<false, tbb::detail::r1::outermost_worker_waiter> (waiter=..., t=warning: RTTI symbol not found for class 'tbb::detail::d1::start_for<tbb::detail::d1::blocked_range<unsigned long>, tbb::detail::d2::parallel_for_body_wrapper<__gnu_cxx::__normal_iterator<mold::elf::ObjectFile<mold::elf::X86_64>**, std::vector<mold::elf::ObjectFile<mold::elf::X86_64>*, std::allocator<mold::elf::ObjectFile<mold::elf::X86_64>*> > >, mold::elf::GdbIndexSection<mold::elf::X86_64>::copy_buf(mold::elf::Context<mold::elf::X86_64>&)::{lambda(mold::elf::ObjectFile<mold::elf::X86_64>*)#1}, mold::elf::ObjectFile<mold::elf::X86_64>*>, tbb::detail::d1::auto_partitioner const>'0x41240021300, this=0x411f82c5000) at /h/sources/mold/third-party/tbb/src/tbb/task_dispatcher.h:322
#10 tbb::detail::r1::task_dispatcher::local_wait_for_all<tbb::detail::r1::outermost_worker_waiter> (waiter=..., t=0x0, this=0x411f82c5000) at /h/sources/mold/third-party/tbb/src/tbb/task_dispatcher.h:463
#11 tbb::detail::r1::arena::process (this=<optimized out>, tls=...) at /h/sources/mold/third-party/tbb/src/tbb/arena.cpp:138
#12 0x0000000000ba810b in tbb::detail::r1::market::process (this=0x411f8230080, j=...) at /h/sources/mold/third-party/tbb/src/tbb/market.cpp:597
#13 0x0000000000baa9a4 in tbb::detail::r1::rml::private_worker::run (this=0x411f8247f00) at /h/sources/mold/third-party/tbb/src/tbb/private_server.cpp:267
#14 0x0000000000baabf9 in tbb::detail::r1::rml::private_worker::thread_routine (arg=<optimized out>) at /h/sources/mold/third-party/tbb/src/tbb/private_server.cpp:221
#15 0x00007ffff67da4f9 in start_thread () from /lib64/libpthread.so.0
#16 0x00007ffff6512f2f in clone () from /lib64/libc.so.6
(gdb) f 2
#2  0x00000000006f0f2a in mold::elf::GdbIndexSection<mold::elf::X86_64>::copy_buf(mold::elf::Context<mold::elf::X86_64>&)::{lambda(mold::elf::ObjectFile<mold::elf::X86_64>*)#1}::operator()(mold::elf::ObjectFile<mold::elf::X86_64>*) const (this=0x411f81145e0, file=0x411f8223c00) at elf/output-chunks.cc:2305
2305          attrs[idx + ++attrs[idx]] = name.attr;
```

- mold commit 0fd6a6ca9093a8bf609fdd7f7be2235402b8b1ee
- gcc 11
- Flags: `-g -gsplit-dwarf -gdwarf=4 -Wa,--compress-debug-sections` and `-Wl,--compress-debug-sections=zlib`

Assuming it's an out of bounds I tried with an ASan build of mold but got no report, even when turning the crashing parallel_for into a regular loop and replacing the atomic accesses with normal ones.

Any info that could help you here?

**Comment by rui314** [comment]
I couldn't reproduce the issue on my machine, so can you share your object file with me?

**Comment by mrichtarsky** [comment]
Unfortunately this reproduces with a lot of object files only (in the case here 400MB) Can you make use of an UndoDB recording of a crashing run? That allows stepping backwards from the failure, and examine variables etc. like regular gdb, without the inputs? (i.e. you would need udb which is available as trial - https://undo.io/ )

**Comment by rui314** [comment]
I might be able to use UndoDB, but in order to use it, I need to reproduce the issue on my machine, no? If your program is open source, I can build it locally.

**Comment by rui314** [comment]
This bug should be fixed in the above commit. Can you verify?

**Comment by mrichtarsky** [comment]
I can confirm that the fix works, thank you very much! :)
