### ISSUE TITLE
mold segfaults when compiling ATS

### ISSUE THREAD

**Issue by vmchale** [rui314/mold#478]
When running

```
mold -run ./configure
mold -run make -j
```

It fails during the link step with

```
make -j4 -C src/CBOOT patsopt \
CCOMP=gcc GCFLAG= LDFLAGS=
make[1]: Entering directory '/tmp/ATS2-Postiats-gmp-0.4.2/src/CBOOT'
ld -r -o libats_libats.o libats_SATS_funmap_avltree_sats.o libats_DATS_funmap_avltree_dats.o libats_SATS_funset_avltree_sats.o libats_DATS_funset_avltree_dats.o libats_SATS_funset_listord_sats.o libats_DATS_funset_listord_dats.o libats_SATS_funmset_listord_sats.o libats_DATS_funmset_listord_dats.o libats_SATS_hashtable_chain_sats.o libats_DATS_hashtable_chain_dats.o libats_SATS_hashtable_linprb_sats.o libats_DATS_hashtable_linprb_dats.o libats_SATS_linqueue_arr_sats.o libats_DATS_linqueue_arr_dats.o libats_SATS_linqueue_lst_sats.o libats_DATS_linqueue_lst_dats.o libats_ngc_SATS_deque_arr_sats.o libats_ngc_DATS_deque_arr_dats.o
make: *** [Makefile:79: src2_patsopt] Segmentation fault (core dumped)
```

Things go as expected with the system ld (GNU ld (GNU Binutils for Ubuntu) 2.34).

(source tarball for the project is [here](https://sourceforge.net/projects/ats2-lang/files/ats2-lang/ats2-postiats-0.4.2/ATS2-Postiats-gmp-0.4.2.tgz)).

**Comment by ishitatsuyuki** [comment]
If you haven't tried already, build the latest main branch of mold, install to your system and try building again.

**Comment by ishitatsuyuki** [comment]
I can reproduce this, and looks like the segfault happens inside `make`, not `mold`. I guess this could be the `mold -run` thing messing up some state?

**Comment by ishitatsuyuki** [comment]
I built GNU Make 4.3 with debug symbols. The crash is always due to an invalid free. (It aborted in the following backtrace, but you can also get a segfault like the OP)

```
#0  0x00007f3ac97f534c in __pthread_kill_implementation () from /usr/lib/libc.so.6
#1  0x00007f3ac97a84b8 in raise () from /usr/lib/libc.so.6
#2  0x00007f3ac9792534 in abort () from /usr/lib/libc.so.6
#3  0x00007f3ac97e9397 in __libc_message () from /usr/lib/libc.so.6
#4  0x00007f3ac97ff33c in malloc_printerr () from /usr/lib/libc.so.6
#5  0x00007f3ac9800ff4 in _int_free () from /usr/lib/libc.so.6
#6  0x00007f3ac9803be3 in free () from /usr/lib/libc.so.6
#7  0x00005588842b128a in start_job_command (child=child@entry=0x558884c25ed0) at src/job.c:1594
#8  0x00005588842b1fe4 in start_waiting_job (c=c@entry=0x558884c25ed0) at src/job.c:1634
#9  0x00005588842b28c0 in new_job (file=0x558884c0d9a0) at src/job.c:1912
#10 0x00005588842c0346 in remake_file (file=0x558884c0d9a0) at src/remake.c:1234
#11 update_file_1 (depth=<optimized out>, file=0x558884c0d9a0) at src/remake.c:835
#12 update_file (file=<optimized out>, depth=<optimized out>) at src/remake.c:336
#13 0x00005588842c0945 in check_dep (file=0x558884c0d9a0, depth=2, depth@entry=1, 
    this_mtime=this_mtime@entry=1772833509675776633, 
    must_make_ptr=must_make_ptr@entry=0x7ffe4c792744) at src/remake.c:1024
#14 0x00005588842bf6f6 in update_file_1 (depth=<optimized out>, file=0x558884be0e30)
    at src/remake.c:572
#15 update_file (file=file@entry=0x558884be0e30, depth=<optimized out>) at src/remake.c:336
#16 0x00005588842c0db4 in update_goal_chain (goaldeps=<optimized out>) at src/remake.c:151
#17 0x00005588842b6813 in main (argc=<optimized out>, argv=<optimized out>, envp=<optimized out>)
    at src/main.c:2589
```

valgrind says that the freed address is on the stack and there doesn't seem to be other corruptions.

That's all I know now. Hope this helps!

**Comment by rui314** [comment]
Thanks for the analysis! I initially thought that 2 is a better solution because it is more robust (i.e. argv could be in .rodata), but at the same time we don't want to allocate heap in this wrapper function, as we have no idea what context this wrapper runs. Since argv can be arbitrary long, we can't copy it to a fixed-length buffer. So I'll fix this in 1.

**Comment by vmchale** [comment]
Thank you for the prompt response!
