### ISSUE TITLE
msan failure

### ISSUE THREAD

**Issue by rui314** [rui314/mold#481]
Currently, mold fails if compiled with MemorySanitizer. This needs fixing.

```
$ make -j`nproc` CXX=clang++-14 CXXFLAGS='-fsanitize=memory -g -Og -fno-omit-frame-pointer' LDFLAGS='-fsanitize=memory -fuse-ld=lld' USE_MIMALLOC=0 test
...
SUMMARY: MemorySanitizer: use-of-uninitialized-value /usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/fs_path.h:1262:14 in std::filesystem::__cxx11::path::filename() const
Exiting
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [Makefile.linux:6: elf/init-array-priorities.sh] Error 1
Testing dead-debug-sections ... ==213403==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x55f8bb84bbf1 in std::filesystem::__cxx11::path::filename() const /usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/fs_path.h:1262:14
    #1 0x55f8bb84b2dd in main /home/ruiu/mold/main.cc:41:45
    #2 0x7f4dd6309d8f in __libc_start_call_main csu/../sysdeps/nptl/libc_start_call_main.h:58:16
...
```

**Comment by azaika** [comment]
I failed to reproduce this in current HEAD (b5bfe4c607b25d19de7d3b451f6ce329a341441b).
Has this already been fixed intentionally? or just resolved luckily?

**Comment by rui314** [comment]
It's still failing on my machine. Maybe it's specific to libstdc++12?

**Comment by azaika** [comment]
It (successfully ?) comes to fail on my machine after I removed my libstdc++ and re-installed libstdc++-12.

But to run the msan, I have to add `CC=clang-14` to the make options. I finally ran the command below.
```
make -j`nproc` CC=clang-14 CXX=clang++-14 CXXFLAGS='-fsanitize=memory -g -Og -fno-omit-frame-pointer' LDFLAGS='-fsanitize=memory -fuse-ld=lld' USE_MIMALLOC=0 test
```

I will try to use libc++ with msan instead of libstdc++ and check whether it fails.

**Comment by etwoo** [comment]
I took a stab at this in https://github.com/rui314/mold/pull/1517.

The main issue is that to avoid false positives in a MemorySanitizer run, all of a project's dependencies need to be built with MemorySanitizer as well. This (somewhat surprisingly) includes the C++ stdlib!

In other words, building mold with MemorySanitizer enabled, then linking against a normal standard library, leads to MemorySanitizer false positives, like the errors re: `std::filesystem` in the bug description.

https://github.com/rui314/mold/pull/1517 includes documentation on how to build an instrumented libc++, link mold against that stdlib, and then collect meaningful MemorySanitizer results, free from these kinds of false positives in the C++ standard library.
