### ISSUE TITLE
Chromium Mac linking error

### ISSUE THREAD

**Issue by water-a** [rui314/mold#702]
```
autoninja -C out/Default chrome
ninja: Entering directory `out/Default'
[389/3614] SOLINK libgfx_shared_mojom_traits.dylib libgfx_shared_mojom_traits.dylib.TOC
FAILED: libgfx_shared_mojom_traits.dylib libgfx_shared_mojom_traits.dylib.TOC 
if [ ! -e "./libgfx_shared_mojom_traits.dylib" -o ! -e "./libgfx_shared_mojom_traits.dylib.TOC" ] || /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/otool -l "./libgfx_shared_mojom_traits.dylib" | grep -q LC_REEXPORT_DYLIB ; then TOOL_VERSION=1662814211 ../../build/toolchain/apple/linker_driver.py -Wcrl,strippath,/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/strip -Wcrl,installnametoolpath,/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/install_name_tool ../../third_party/llvm-build/Release+Asserts/bin/clang++ -shared  -Wl,-install_name,@rpath/"libgfx_shared_mojom_traits.dylib" -Werror -fuse-ld=mold -Wl,-fatal_warnings -Wl,--color-diagnostics -arch arm64 -no-canonical-prefixes -nostdlib++ -isysroot ../../../../../../../Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk -mmacos-version-min=10.13 -Wl,-ObjC -Wl,-rpath,@loader_path/. -Wl,-rpath,@loader_path/../../.. -o "./libgfx_shared_mojom_traits.dylib" "@./libgfx_shared_mojom_traits.dylib.rsp" && { /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/otool -l "./libgfx_shared_mojom_traits.dylib" | grep LC_ID_DYLIB -A 5; /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/nm -gPp "./libgfx_shared_mojom_traits.dylib" | cut -f1-2 -d' ' | grep -v U$$; true; } > "./libgfx_shared_mojom_traits.dylib.TOC"; else TOOL_VERSION=1662814211 ../../build/toolchain/apple/linker_driver.py -Wcrl,strippath,/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/strip -Wcrl,installnametoolpath,/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/install_name_tool ../../third_party/llvm-build/Release+Asserts/bin/clang++ -shared  -Wl,-install_name,@rpath/"libgfx_shared_mojom_traits.dylib" -Werror -fuse-ld=mold -Wl,-fatal_warnings -Wl,--color-diagnostics -arch arm64 -no-canonical-prefixes -nostdlib++ -isysroot ../../../../../../../Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk -mmacos-version-min=10.13 -Wl,-ObjC -Wl,-rpath,@loader_path/. -Wl,-rpath,@loader_path/../../.. -o "./libgfx_shared_mojom_traits.dylib" "@./libgfx_shared_mojom_traits.dylib.rsp" && { /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/otool -l "./libgfx_shared_mojom_traits.dylib" | grep LC_ID_DYLIB -A 5; /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/nm -gPp "./libgfx_shared_mojom_traits.dylib" | cut -f1-2 -d' ' | grep -v U$$; true; } > "./libgfx_shared_mojom_traits.dylib.tmp" && if ! cmp -s "./libgfx_shared_mojom_traits.dylib.tmp" "./libgfx_shared_mojom_traits.dylib.TOC"; then mv "./libgfx_shared_mojom_traits.dylib.tmp" "./libgfx_shared_mojom_traits.dylib.TOC" ; fi; fi
clang++: error: unable to execute command: Segmentation fault: 11
clang++: error: linker command failed due to signal (use -v to see invocation)
Traceback (most recent call last):
  File "../../build/toolchain/apple/linker_driver.py", line 356, in <module>
    LinkerDriver(sys.argv).run()
  File "../../build/toolchain/apple/linker_driver.py", line 140, in run
    subprocess.check_call(compiler_driver_args, env=env)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['../../third_party/llvm-build/Release+Asserts/bin/clang++', '-shared', '-Wl,-install_name,@rpath/libgfx_shared_mojom_traits.dylib', '-Werror', '-fuse-ld=mold', '-Wl,-fatal_warnings', '-Wl,--color-diagnostics', '-arch', 'arm64', '-no-canonical-prefixes', '-nostdlib++', '-isysroot', '../../../../../../../Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk', '-mmacos-version-min=10.13', '-Wl,-ObjC', '-Wl,-rpath,@loader_path/.', '-Wl,-rpath,@loader_path/../../..', '-o', './libgfx_shared_mojom_traits.dylib', '@./libgfx_shared_mojom_traits.dylib.rsp']' returned non-zero exit status 1.
[400/3614] CXX obj/chrome/browser/browser/enterprise_util.o
ninja: build stopped: subcommand failed.
```

Running this build on the M1 Macbook Pro

Let me know if you need any other information.

**Comment by niklaskorz** [comment]
I can reproduce this issue on an M1 Pro with macOS 12.6, mold 1.6, Rust 1.64.0 and Clang 14.0.0, in my case for a Rust project linking to ffmpeg libraries:

```
error: linking with `clang` failed: exit status: 254
  |
  = note: "clang" "-arch" "arm64" <lots of object files> "-lssl" "-lcrypto" "-framework" "CoreFoundation" "-framework" "Security" "-lavcodec" "-lavformat" "-lavutil" "-lswresample" "-lswscale" "-liconv" "-lSystem" "-lresolv" "-lc" "-lm" "-liconv" "-L" "/Users/niklaskorz/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/aarch64-apple-darwin/lib" "-o" "/Users/niklaskorz/Development/rust-project/target/debug/deps/rust_project-91c8de2fd2d63fc7" "-Wl,-dead_strip" "-nodefaultlibs" "-fuse-ld=mold"
  = note: clang: error: unable to execute command: Segmentation fault: 11
          clang: error: linker command failed due to signal (use -v to see invocation)
```
