### ISSUE TITLE
mold 1.5.0 produces unloadable aarch64 ELF binary with extension thunks

### ISSUE THREAD

**Issue by sicherha** [rui314/mold#737]
The `range-extension-thunk.sh` test fails with mold 1.5.0 on aarch64 Linux with the following error message:
```
out/test/elf/aarch64/range-extension-thunk/exe: error while loading shared libraries:
cannot apply additional memory protection after relocation: Cannot allocate memory
```
Judging by the output of `strace`, it seems the error occurs not in the binary but within the dynamic loader itself:
```
execve("./exe", ["./exe"], 0x7ff7a60e50 /* 22 vars */) = 0
brk(NULL)                               = 0x558ef67000
faccessat(AT_FDCWD, "/etc/ld.so.preload", R_OK) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=31085, ...}) = 0
mmap(NULL, 31085, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7f8af63000
close(3)                                = 0
openat(AT_FDCWD, "/lib/aarch64-linux-gnu/libc.so.6", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0\267\0\1\0\0\0`\17\2\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=1455120, ...}) = 0
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f8af61000
mmap(NULL, 1527752, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f8adc8000
mprotect(0x7f8af25000, 61440, PROT_NONE) = 0
mmap(0x7f8af34000, 24576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x15c000) = 0x7f8af34000
mmap(0x7f8af3a000, 12232, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f8af3a000
close(3)                                = 0
mprotect(0x7f8af34000, 16384, PROT_READ) = 0
mprotect(0x5570f30000, 65536, PROT_READ) = -1 ENOMEM (Cannot allocate memory)
writev(2, [{iov_base="./exe", iov_len=5}, {iov_base=": ", iov_len=2}, {iov_base="error while loading shared libra"..., iov_len=36}, {iov_base=": ", iov_len=2}, {iov_base="", iov_len=0}, {iov_base="", iov_len=0}, {iov_base="cannot apply additional memory p"..., iov_len=58}, {iov_base=": ", iov_len=2}, {iov_base="Cannot allocate memory", iov_len=22}, {iov_base="\n", iov_len=1}], 10./exe: error while loading shared libraries: cannot apply additional memory protection after relocation: Cannot allocate memory
) = 128
exit_group(127)                         = ?
+++ exited with 127 +++
```
Nothing suspicious jumped my eye when examining the binary with `readelf` - but admittedly I'm not sure what exactly to look for.

You can find the output files produced by the test here: https://www4.cs.fau.de/~erhardt/foo/mold/range-extension-thunk/

**Comment by sicherha** [comment]
GDB backtrace from the loader:
```
(gdb) bt 
#0  mprotect () at ../sysdeps/unix/syscall-template.S:120
#1  0x0000007ff7fd76d8 in _dl_protect_relro (l=0x7ff7fff220) at dl-reloc.c:337
#2  0x0000007ff7fd8428 in _dl_relocate_object (l=l@entry=0x7ff7fff220, scope=<optimized out>, 
    reloc_mode=<optimized out>, consider_profiling=<optimized out>, consider_profiling@entry=0x0)
    at dl-reloc.c:322
#3  0x0000007ff7fd0898 in dl_main (phdr=<optimized out>, phnum=<optimized out>, 
    user_entry=<optimized out>, auxv=<optimized out>) at rtld.c:2310
#4  0x0000007ff7fe22a4 in _dl_sysdep_start (start_argptr=start_argptr@entry=0x7ffffff4b0, 
    dl_main=dl_main@entry=0x7ff7fce690 <dl_main>) at ../elf/dl-sysdep.c:252
#5  0x0000007ff7fcdc5c in _dl_start_final (arg=arg@entry=0x7ffffff4b0, 
    info=info@entry=0x7fffffefe8) at rtld.c:485
#6  0x0000007ff7fcdec8 in _dl_start (arg=<optimized out>) at rtld.c:577
#7  0x0000007ff7fcd148 in _start () from /lib/ld-linux-aarch64.so.1
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
(gdb) frame 1
#1  0x0000007ff7fd76d8 in _dl_protect_relro (l=0x7ff7fff220) at dl-reloc.c:337
337     in dl-reloc.c
(gdb) p *l
$6 = {l_addr = 0x5555550000, l_name = 0x7ff7fff800 "", l_ld = 0x55655604a0, l_next = 0x7ff7fff810, 
  l_prev = 0x0, l_real = 0x7ff7fff220, l_ns = 0x0, l_libname = 0x7ff7fff7e8, l_info = {0x0, 
    0x55655604b0, 0x5565560500, 0x5565560520, 0x0, 0x5565560550, 0x5565560530, 0x55655604c0, 
    0x55655604d0, 0x55655604e0, 0x5565560560, 0x5565560540, 0x5565560600, 0x5565560610, 0x0, 0x0, 
    0x0, 0x0, 0x0, 0x0, 0x5565560510, 0x5565560640, 0x0, 0x55655604f0, 0x0, 0x5565560570, 
    0x55655605b0, 0x5565560580, 0x55655605c0, 0x0, 0x0, 0x0, 0x5565560590, 0x55655605a0, 0x0, 0x0, 
    0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x55655605f0, 0x55655605e0, 0x0, 0x0, 0x5565560630, 
    0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x55655605d0, 0x0 <repeats 25 times>, 
    0x5565560620}, l_phdr = 0x5555550040, l_entry = 0x5565550070, l_phnum = 0xe, l_ldnum = 0x0, 
  l_searchlist = {r_list = 0x7ff7ff0570, r_nlist = 0x3}, l_symbolic_searchlist = {
    r_list = 0x7ff7fff7e0, r_nlist = 0x0}, l_loader = 0x0, l_versions = 0x7ff7ff0590, 
  l_nversions = 0x3, l_nbuckets = 0x1, l_gnu_bitmask_idxbits = 0x0, l_gnu_shift = 0x1a, 
  l_gnu_bitmask = 0x55555503c0, {l_gnu_buckets = 0x55555503c8, l_chain = 0x55555503c8}, {
    l_gnu_chain_zero = 0x55555503b4, l_buckets = 0x55555503b4}, l_direct_opencount = 0x1, 
  l_type = lt_executable, l_relocated = 0x1, l_init_called = 0x0, l_global = 0x1, 
  l_reserved = 0x0, l_phdr_allocated = 0x0, l_soname_added = 0x0, l_faked = 0x0, 
  l_need_tls_init = 0x0, l_auditing = 0x0, l_audit_any_plt = 0x0, l_removed = 0x0, 
  l_contiguous = 0x0, l_symbolic_in_local_scope = 0x0, l_free_initfini = 0x0, 
  l_nodelete_active = 0x0, l_nodelete_pending = 0x0, l_rpath_dirs = {dirs = 0xffffffffffffffff, 
    malloced = 0x0}, l_reloc_result = 0x0, l_versyms = 0x55555504c2, l_origin = 0x0, 
  l_map_start = 0x5555550000, l_map_end = 0x557555007c, l_text_end = 0x557555007c, l_scope_mem = {
    0x7ff7fff528, 0x0, 0x0, 0x0}, l_scope_max = 0x4, l_scope = 0x7ff7fff5d0, l_local_scope = {
    0x7ff7fff528, 0x0}, l_file_id = {dev = 0x0, ino = 0x0}, l_runpath_dirs = {
    dirs = 0xffffffffffffffff, malloced = 0x0}, l_initfini = 0x7ff7ff0550, l_reldeps = 0x0, 
  l_reldepsmax = 0x0, l_used = 0x1, l_feature_1 = 0x0, l_flags_1 = 0x8000000, l_flags = 0x0, 
  l_idx = 0x0, l_mach = {plt = 0x0, tlsdesc_table = 0x0}, l_lookup_cache = {sym = 0x5555550430, 
    type_class = 0x4, value = 0x7ff7ff0000, ret = 0x7ff7e66200}, l_tls_initimage = 0x0, 
  l_tls_initimage_size = 0x0, l_tls_blocksize = 0x0, l_tls_align = 0x0, 
  l_tls_firstbyte_offset = 0x0, l_tls_offset = 0x0, l_tls_modid = 0x0, l_tls_dtor_count = 0x0, 
  l_relro_addr = 0x100104a0, l_relro_size = 0xfb60, l_serial = 0x0}
```

**Comment by rui314** [comment]
This is probably the same issue as https://github.com/rui314/mold/issues/732
